language: python
python:
    - "3.5"
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
install:
    - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip setuptools numpy scipy matplotlib pandas
    - pip install coverage
    - pip install nose
    - pip install coveralls
    - python setup.py install
script:
    - python setup.py nosetests
after_success:
    - coveralls
